server:
  port: 8082
  servlet:
    context-path: /post

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  # Database
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/buildingadmin"
    username: buildingadmin
    password: buildingadmin
    driver-class-name: org.postgresql.Driver
  data.mongodb:
    authentication-database: admin
    database: buildingadmin
    host: localhost
    port: 27017
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/nartan-ba


