# Spring properties
spring:  
    # Database
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password:
#  security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
#           jwk-set-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/certs
    
server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO