CREATE OR REPLACE FUNCTION public.update_modification_time ()
RETURNS trigger AS
$BODY$
DECLARE
BEGIN
  NEW.MODIFICATION_TIME = CLOCK_TIMESTAMP();
  RAISE NOTICE 'UPDATING MODIFICATION_TIME, NEW VALUE=<%>', NEW.MODIFICATION_TIME;
  RETURN NEW;
END;
$BODY$
LANGUAGE PLpgSQL
CALLED ON NULL INPUT
IMMUTABLE
EXTERNAL SECURITY DEFINER;


ALTER FUNCTION public.update_modification_time () OWNER TO buildingadmin;
